let name="Sunitha";
var age=20;
let isstudent=true;
let favouritecolor;
let futureplans=null;
let b=Math.ceil(Math.random()*100);
const add=age+b;
const sub=age-18;
const mul=age*2;
const mod=age/5;
const c5=age**2;
let c6=age++;
let c7=age--;
console.log("This is addition",add);
console.log(sub);
console.log(mul);
console.log(mod);
console.log(c5);
console.log(c6);
console.log(c7);
let gt=age>18;
let equal=age==b;
let nameequal=name=="Himaja";
console.log(gt);
console.log(equal);
console.log(nameequal);
let and=age>=18&&isstudent;
let or=age<=18||!isstudent;
console.log(and);
console.log(or);
    
