let courses=["HTML","CSS","JS","JAVA"];
console.log(courses.length);
let string=courses.toString();
console.log(string);
console.log(courses.join('^'));
let courses1=["c","c++","python","Java"];
let newArray=courses.concat(courses1);
console.log(newArray);
console.log("Reversing the Elements",courses.reverse());
console.log("Sorting the Elements",courses.sort());
console.log("Including method",courses.includes("JS"));
console.log("Index of the Element",courses.indexOf("JAVA"));
console.log("Removing First element",courses.shift());
console.log("Poping the Elements",courses.pop());
console.log("Pushing the Elements",courses.push("Sql"));